-- MySQL Script generated by MySQL Workbench
-- mié 10 oct 2018 18:48:02 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema trolleyes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema trolleyes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `trolleyes` DEFAULT CHARACTER SET utf8 ;
USE `trolleyes` ;

-- -----------------------------------------------------
-- Table `trolleyes`.`tipoUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trolleyes`.`tipoUsuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `desc` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `trolleyes`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trolleyes`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dni` VARCHAR(255) NULL,
  `nombre` VARCHAR(255) NULL,
  `ape1` VARCHAR(255) NULL,
  `ape2` VARCHAR(255) NULL,
  `login` VARCHAR(255) NULL,
  `pass` VARCHAR(512) NULL,
  `id_tipoUsuario` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_tipoUsuario_idx` (`id_tipoUsuario` ASC),
  CONSTRAINT `fk_usuario_tipoUsuario`
    FOREIGN KEY (`id_tipoUsuario`)
    REFERENCES `trolleyes`.`tipoUsuario` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `trolleyes`.`tipoProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trolleyes`.`tipoProducto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `desc` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `trolleyes`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trolleyes`.`producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(255) NULL,
  `desc` VARCHAR(255) NULL,
  `existencias` INT NULL,
  `precio` FLOAT NULL,
  `foto` VARCHAR(512) NULL,
  `id_tipoProducto` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_producto_tipoProducto1_idx` (`id_tipoProducto` ASC),
  CONSTRAINT `fk_producto_tipoProducto1`
    FOREIGN KEY (`id_tipoProducto`)
    REFERENCES `trolleyes`.`tipoProducto` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `trolleyes`.`factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trolleyes`.`factura` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL,
  `iva` FLOAT NULL,
  `id_usuario` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_factura_usuario1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_factura_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `trolleyes`.`usuario` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `trolleyes`.`linea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trolleyes`.`linea` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NULL,
  `id_producto` INT NULL,
  `id_factura` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_linea_producto1_idx` (`id_producto` ASC),
  INDEX `fk_linea_factura1_idx` (`id_factura` ASC),
  CONSTRAINT `fk_linea_producto1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `trolleyes`.`producto` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_linea_factura1`
    FOREIGN KEY (`id_factura`)
    REFERENCES `trolleyes`.`factura` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
